PLF-6687 Remove the hardcode of portal site name in source code
exoplatform/integration pull request #172
Opened 2017-02-02 09:55 UTC by nttuyen

2017-02-15 08:04 UTC, thomasdelhomenie requested changes

2017-02-15 08:04 UTC, thomasdelhomenie commented on integ-forum/integ-forum-social/src/main/java/org/exoplatform/forum/ext/activity/BuildLinkUtils.java
> +    return buildLink(parentObjectId, objectId, portletInfo, Util.getPortalRequestContext().getSiteName());
Could be replaced by CommonsUtils.getCurrentSite().

2017-02-15 10:34 UTC, nttuyen commented on integ-forum/integ-forum-social/src/main/java/org/exoplatform/forum/ext/activity/BuildLinkUtils.java
> +    return buildLink(parentObjectId, objectId, portletInfo, Util.getPortalRequestContext().getSiteName());
yes, it has been replaced

2017-02-15 16:59 UTC, thomasdelhomenie approved these changes

2017-02-20 14:16 UTC, thomasdelhomenie commented
Moved to https://github.com/exodev/integration/pull/105

2017-02-20 14:16 UTC, closed without merging